version: '3'
services:
  web:
    # Uncomment the next line to use a non-root user for all processes.
    # See https://aka.ms/vscode-remote/containers/non-root for details.
    # user: node

    build:
      context: .
      dockerfile: Dockerfile
      args:
        # Update VARIANT to pick a node version: 14, 12, 10
        VARIANT: "3.1-bionic"
        INSTALL_NODE: "true"
        # On Linux, you may need to update USER_UID and USER_GID below if not your local UID is not 1000.
        USER_UID: 1000
        USER_GID: 1000

    volumes:
      - ..:/workspace:cached

    depends_on:
        - sql

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    links:
      - sql

  sql:
    image: "mcr.microsoft.com/mssql/server"
    environment:
        SA_PASSWORD: "Umbrac0R0cks!"
        ACCEPT_EULA: "Y"
    ports:
        - 1433:1433
    hostname:
        - dbserver

